version: '3'

services:
  django:
    volumes:
      - static:/usr/src/app/static
    build:
      context: ./
      dockerfile: Dockerfile
    image: sergey1701/django-test:0.0.6
    ports:
      - 8000

  nginx:
    volumes:
      - static:/static
    build:
      context: ./nginx
      dockerfile: Dockerfile    
      
    ports: 
      - 8000:8000 
    depends_on:
      - django

volumes:
  static:      