name: Docker Hub CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, update-readme ]
  pull_request:
    branches: [ main, update-readme ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout 
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      

      - name: Build Docker Container
        run: docker-compose up -d --build

      - name: Push Docker Conteiner
        uses: c-py/action-dotenv-to-setenv@v2
        with:
          env-file: ./.env
        run: docker push ${{ 'IMAGE_NAME' }}